Repository OpenTreeMap/otm-core, pull requests merged in 2018-03, with the labels that each got.

#3235 Added option to change password from user profile
  opentreemap/treemap/templates/registration/password_change_done.html
  opentreemap/treemap/templates/registration/password_change_form.html
  opentreemap/treemap/templates/treemap/user.html
Labels: queue

#3234 Added the ability to zoom to the current geo loc
  opentreemap/treemap/js/src/lib/MapManager.js
  package.json
  yarn.lock
Labels: queue

#3237 Fixed issue diameter value is not showing directly below diameter field.
  opentreemap/treemap/templates/treemap/field/diameter_div.html
  opentreemap/treemap/templates/treemap/field/diameter_tr.html
  opentreemap/treemap/templates/treemap/field/div.html
  opentreemap/treemap/templates/treemap/partials/diameter_calculator.html
  opentreemap/treemap/templates/treemap/partials/diameter_video.html
Labels: queue

#3239 Store current base map in local storage
  opentreemap/treemap/js/src/lib/MapManager.js
Labels: queue

#3242 Fixed current location popping out of bounds
  opentreemap/treemap/js/src/mapPage/addMapFeature.js
  opentreemap/treemap/templates/treemap/partials/step_set_location.html
Labels: in progress

#3243 Update moment to 2.19.3
  package.json
  yarn.lock
Labels: in progress

#3244 Incorporate the basemap provider into selected basemap storage
  opentreemap/treemap/js/src/lib/MapManager.js
Labels: in review
